events {
    worker_connections 1024; # Maximum number of connections per worker
}


http {
    upstream flask_app {
        server matrix-edge-tts:8000;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://flask_app;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}