import { ILocalizer } from "./localizer";

export class LocalizerSimplifiedChinese implements ILocalizer {
    locale = 'zh-CN';
    private dictionary = new Map<string, string>(
        [
            ['Settings', '设置'],
            ['Adjust setting for your comfortable', '调整设置以适合您的使用习惯'],
            ['Save', '保存'],
            ['Language', '语言'],
            ['Theme', '主题'],
            ['Select your language', '选择语言'],
            ['Select your theme', '选择主题'],
            ['Dark', '暗黑'],
            ['Light', '浅色'],
            ['Receive email when there is new content', '当有新内容时接收电子邮件通知'],
            ['Blog', '博客'],
            ['Plans', '计划'],
            ['Subscribe', '订阅'],
            ['Contact', '联系'],
            ['About', '关于'],
            ['Welcome', '欢迎'],
            ['Discover', '发现'],
            ['Artists', '作家'],
            ['Library', '我的书库'],
            ['Home', '首页'],
            ['My Account', '我的账户'],
            ['Account', '账户'],
            ['Profile', '个人资料'],
            ['Sign Out', '退出'],
            ['Sign In', '登录'],
            ['Log in', '登录'],
            ['Password', '密码'],
            ['Welcome back', '欢迎回来'],
            ['Create a new account', '创建新账户'],
            ['Forgot password', '忘记密码'],
            ['Register', '注册'],
            ['Search', '搜索'],
            ['Contact Us', '联系我们'],
            ['Subject', '主题'],
            ['minimum length 10 chars', '最少10个字符'],
            ['Message', '消息'],
            ['What do you want us know?', '您想让我们知道什么？'],
            ['minimum length 50 chars, maximum length 500 chars', '最少50个字符，最多500个字符'],
            ['Characters left', '剩余字符'],
            ['Send', '发送'],
            ['Cancel', '取消'],
            ['Delete', '删除'],
            ['Are you sure you want to delete?', '您确定要删除吗？'],
            ['Yes', '是'],
            ['No', '否'],
            ['FAQs', '常见问题'],
            ['New Releases', '最新发布'],
            ['Show more', '显示更多'],
            ['Suggesttions', '热门推荐'],
            ['Suggests', '热门推荐'],
            ['Likes', '最受欢迎'],
            ['Most Likes', '最受欢迎'],
            ['New Authors', '新作家'],
            ['Popular Authors', '热门作家'],
            ['My History', '我的收听'],
            ['My Favorites', '我的收藏'],
            ['My Play Plan', '我的播放计划'],
            ['My Play History', '我的播放历史'],
            ['My Downloads', '我的下载'],
            ['Recents', '最新发布'],
            ['Find a author', '查找作家'],
            ['All Authors', '所有作家'],
            ['What do you want to listen to?', '您想听什么？'],
            ['Categories', '分类'],
            ['Most Play This Week', '本周最受欢迎'],
            ['Most Play This Month', '本月最受欢迎'],
            ['Most Play This Year', '本年最受欢迎'],
            ['Autobiography', '自传'],
            ['Fiction', '小说'],
            ['History', '历史'],
            ['Mystery', '悬疑'],
            ['Political', '政治'],
            ['Religion', '宗教'],
            ['Science', '科学'],
            ['Sexuality', '两性'],
            ['Travel', '旅行'],
            ['Duration', '时长'],
            ['Like', '喜欢'],
            ['Favorite', '收藏'],
            ['Add to my play list', '添加到我的播放计划'],
            ['Download', '下载'],
            ['Share', '分享'],
            ['Play', '播放'],
            ['Choose the plan that best fits your needs. Whether you are just getting started or need advanced features, there is a plan for you.', '选择最适合您的计划。无论您是刚刚入门还是需要高级功能，都有适合您的'],
            ['Add to Cart', '添加到购物车'],
            ['Have questions?', '有问题？'],
            ['Check here first', '先看看这里'],
            ['Free', '免费'],
            ['Silver', '银牌'],
            ['Gold', '金牌'],
            ['Total', '总计'],
            ['month', '月'],
            ['6 month', '6个月'],
            ['year', '年'],
            ['Monthly', '每月'],
            ['Semiannual', '半年'],
            ['Annual', '每年'],
            ['Shopping Cart', '购物车'],
            ['Your cart is filled with great choices! Take a moment to review your selections and prepare for an enriching listening experience with your chosen audiobooks. Once you are ready, proceed to checkout to secure your titles and embark on your auditory adventure.', '您的购物车中装满了精彩的选择！花点时间回顾您的选择，并为您所选的有声书准备一次丰富的听觉体验。一旦您准备好，请继续结账以确保您的标题并开始您的听觉冒险。'],
            ['Your cart is empty', '您的购物车为空'],
            ['Product', '产品'],
            ['Price', '价格'],
            ['Quantity', '数量'],
            ['Discount', '折扣'],
            ['Total After Discount', '折后总计'],
            ['Actions', '操作'],
            ['Promo code', '优惠码'],
            ['Clear promo code', '清除优惠码'],
            ['Redeem', '兑换'],
            ['Proceed to Checkout', '继续结账'],
            ['Order Summary', '订单摘要'],
            ['Tax', '税费'],
            ['Subtotal', '小计'],
            ['Processing fee', '处理费'],
            ['Checkout', '结账'],
            ['You are almost there! Review your order and get ready to enjoy your audiobooks.', '您快到了！回顾您的订单并准备享受您的有声书。'],
            ['Billing address', '账单地址'],
            ['First name', '名'],
            ['Last name', '姓'],
            ['Display Name', '显示名称'],
            ['Address', '地址'],
            ['Address 2 (optional)', '地址2（可选）'],
            ['Country', '国家'],
            ['State', '州'],
            ['City', '城市'],
            ['Zip Code', '邮政编码'],
            ['Payment', '付款'],
            ['Save this information for next time', '下次保存此信息'],
            ['Credit card', '信用卡'],
            ['Name on card', '卡上姓名'],
            ['Full name as displayed on card', '卡上姓名'],
            ['Name on card is required', '卡上姓名是必填项'],
            ['Credit card number', '信用卡号码'],
            ['Card Number', '卡号'],
            ['Expiration date', '到期日期'],
            ['Expiration date required', '到期日期是必填项'],
            ['CVV', 'CVV'],
            ['Card information will not be persisted for future use.', '卡信息不会被保存以供将来使用。'],
            ['Please provide a valid state.', '请提供有效的州。'],
            ['Please select a valid city.', '请选择有效的城市。'],
            ['Please select a valid country.', '请选择有效的国家。'],
            ['Please enter your shipping billingAddress.', '请输入您的账单地址。'],
            ['Valid last name is required.', '姓是必填项。'],
            ['Valid first name is required.', '名是必填项。'],
            ['Password is required.', '密码是必填项。'],
            ['New password is required.', '新密码是必填项。'],
            ['Confirm password is required.', '确认密码是必填项。'],
            ['Apartment or suite', '公寓或套房'],
            ['1234 Main St', '1234 主街'],
            ['Choose', '请选择'],
            ['Other', '其他'],
            ['Loading...', '加载中...'],
            ['Close', '关闭'],
            ['No favorite album found', '没有找到收藏的书'],
            ['No downloaded album found', '没有找到下载的书'],
            ['No play history found', '没有找到播放历史'],
            ['No album added to the plan', '没有添加到播放计划的书'],
            ['No favorite albums found', '没有找到收藏的书'],
            ['Register at', '注册于'],
            ['Last login', '上次登录'],
            ['Current Subscription', '当前订阅'],
            ['Start Date', '开始日期'],
            ['End Date', '结束日期'],
            ['Email', '电子邮件'],
            ['Email address', '电子邮件地址'],
            ['Old Password', '旧密码'],
            ['New Password', '新密码'],
            ['Confirm Password', '确认密码'],
            ['Reset', '重置'],
            ['Upgrade', '升级'],
            ['Plans you can upgrade to', '您可以升级到的计划'],
            ['Reset Password', '重置密码'],
            ['Change Plan', '更改计划'],
            ['Upgrade Plan', '升级计划'],
            ['Billing Information', '账单信息'],
            ['Reset your password', '重置您的密码'],
            ['Change your subscription plan', '更改您的订阅计划'],
            ['Upgrade your suscription plan to have ore features', '升级您的订阅计划以获得更多功能'],
            ['Update your billing information', '更新您的账单信息'],
            ['Read', '阅读'],
            ['books', '书'],
            ['Bio', '简介'],
            ['Write something about yourself', '写点关于自己的话'],
            ['as a new user', '作为新用户'],
            ['Already have an account?', '已经有账户？'],
            ['Reset your password with your registered email address', '使用您的注册电子邮件地址重置密码'],
            ['Your display name', '您的显示名称'],
            ['Payment succeeded', '付款成功'],
            ['Payment failed', '付款失败'],
            ['Your payment was successful, thank you for your purchase!', '您的付款成功，感谢您的购买！'],
            ['Your payment was failed, please try again later.', '您的付款失败，请稍后再试。'],
            ['History', '历史'],
            ['Events', '事件'],
            ['People', '人物'],
            ['Articles', '文章'],
            ['Matrix Audio', '深夜书屋'],
            ['Books', '书籍'],
            ['Episodes', '章节'],
            ['Hours', '小时'],
            ['Authors', '作者'],
            ['Email Here', '电子邮件'],
            ['Discover the rich history that has shaped our journey and achievements.', '探索塑造我们旅程和成就的丰富历史。'],
            ['Stay updated with our latest events and happenings around the globe.', '随时了解在全球范围内的最新活动和动态。'],
            ['Meet the incredible people who make our community vibrant and dynamic.', '认识那些让我们的生活充满活力和活力的令人难以置信的人。'],
            ['Explore a wide range of articles written by experts and enthusiasts.', '探索由专家和爱好者撰写的各种文章。'],
            ['Welcome to Matrix Audio, your premier destination for high-quality, diverse audiobooks. Our mission is to provide readers with an extensive collection of audio content that caters to all tastes and preferences, ensuring a seamless and enriching listening experience.', '欢迎来到深夜书屋，您高品质、多样化有声书的首选目的地。我们的使命是为读者提供丰富的音频内容，满足所有口味和偏好，确保无缝和丰富的听觉体验。'],
            ['A vast collection of books curated for your reading pleasure.', '为您的阅读乐趣精心策划的丰富书籍。'],
            ['Engaging episodes that keep you hooked from start to finish.', '引人入胜的剧集让您从头到尾都着迷。'],
            ['Thousands of hours of content to explore and enjoy.', '的精彩内容'],
            ['Talented authors who bring stories to life.', '才华横溢的作家让故事栩栩如生。'],
            ['Be the first to see the news', '成为第一个看到消息的人'],
            ['Subscribe with your email to get notification about new books, episods and articles.', '订阅您的电子邮件以获取有关新书、作者和文章的通知。'],
            ['My Orders', '我的订单'],
            ['Order ID', '订单编号'],
            ['Status', '状态'],
            ['Product', '产品'],
            ['Price', '价格'],
            ['Date', '日期'],
            ['Collections', '合集'],
        ]
    );

    translate(value: string): string {
        if (this.dictionary.has(value)) {
            return this.dictionary.get(value) || value;
        }
        return value;
    }
}
